arcv: Fix LMUL type mismatch in arcv_vmv_v_s intrinsics.
According to the latest spec the __riscv_arcv_vmv_v_s_* intrinsics incorrectly
required the vs2 operand to match the destination LMUL.  Per the instruction
semantics, vs2 should always be LMUL=1 regardless of destination LMUL.

This caused type errors like:
  vint8m2_t result = __riscv_arcv_vmv_v_s_i8m2(vd, vs2, rs1, vl);
                                                    ^~~
  error: incompatible type for argument 2
  note: expected 'vint8m2_t' but argument is of type 'vint8m1_t'

This patch changes v_sx_args to use RVV_BASE_lmul1_vector for the second
argument, updates the MD pattern to accept <V_LMUL1> for operand 2 and
modifies the expander to pass vs2 with its actual LMUL=1 mode.

Additional tests were added.

Signed-off-by: Luis Silva <luiss@synopsys.com>